#!/bin/sh


usage() {
cat << EOF
Usage: drac_confing action server...
 action   - action to perform:
  view		 - connect to KVM
  racreset	 - restart DRAC
  clrsel	 - clear DRAC sel
  powerup	 - power on
  powerdown  - power off
  hardreset  - hard reset
  createraid - build a RAID1 of 2 first disks
  deleteraid - delete any existing RAIDs
  deployssl  - deploy ssl certs and settings
 server   - one or more servers to connect to
EOF
}

if [ -z "$1" ]; then
	echo "Give me action to perform!"
	usage
	exit 1
fi
action=$1

shift
if [ -z "$1" ]; then
	echo "Give me name of the server!"
	usage
	exit 1
fi

workdir=$(dirname $0)
oldpwd=$(pwd)
cd $workdir
export workdir=$(pwd)
export libdir=$workdir/lib
cd $oldpwd

. $workdir/config

if [ ! -f $RACADM ]; then
	echo "I could not find racadm binary $RACADM"
	exit 1
fi

while [ $# -ne 0 ]; do
	export host=$1
	export racadm="$RACADM -u ${USER} -p ${PASS} -r $host"
	
	ractype=$( ($racadm get iDRAC.Info | grep '#Type=' || $racadm  getconfig -g idracinfo | grep 'idRacType=' ) | tr -d '\r' | tr -d '\n' | cut -d '=' -f 2)

	case "$ractype" in
		8)
			export model="M1000e"
			;;
		10|11)
			export model="iDRAC6"
			;;
		16|17)
			export model="iDRAC7"
			;;
		32|33)
			export model="iDRAC8"
			;;
		*)
			echo "Unsupported ractype $ractype"
			exit 1
			;;
	esac

	echo " --- Working on $host, $model --- "

	case "$action" in
		"view")
			sh $libdir/view.sh
			;;
		"racreset")
			$racadm racreset
			;;
		"clrsel")
			$racadm clrsel
			;;
		"powerup")
			$racadm serveraction $action
			;;
		"powerdown")
			$racadm serveraction $action
			;;
		"hardreset")
			$racadm serveraction $action
			;;
		"createraid")
			sh $libdir/raid.sh $action
			;;
		"deleteraid")
			sh $libdir/raid.sh $action
			;;
		"deployssl")
			sh $libdir/deployssl.sh
			;;
		"setntp")
			sh $libdir/ntp.sh $action
			;;
		*)
			echo "Uknown server action specified"
			;;
	esac

	echo " --- Work on $host is finished --- "
	echo
	shift
done
